# Generated by Django 4.2.3 on 2023-07-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='teste',
        ),
    ]
